services:
  firewall:
    image: dimajix/docker-firewall
    build:
      context: .
    network_mode: host
    #environment:
    #  no_proxy: ${no_proxy}
    #  http_proxy: ${http_proxy}
    #  https_proxy: ${https_proxy}

  http-bridge:
    image: httpd:2.2-alpine
    labels:
      - dfw.enabled=true
      - dfw.input.default=deny
      #- dfw.input.rule.0=allow proto icmp
      - dfw.input.rule.1=allow on eth0 proto tcp from 0.0.0.0/0 port 80
      - dfw.output.default=deny
      #- dfw.output.rule.2=allow proto tcp to 192.168.150.6 port 8080
      #- dfw.output.rule.3=deny on eth0 to 0.0.0.0/0
    networks:
      - firewall-bridge

  http-macvlan:
    image: httpd:2.2-alpine
    labels:
      - dfw.enabled=true
      - dfw.input.default=deny
      #- dfw.input.rule.0=allow proto icmp
      #- dfw.input.rule.1=allow on eth0 proto tcp from 0.0.0.0/0 port 80
      - dfw.output.default=deny
      #- dfw.output.rule.2=allow proto tcp to 192.168.150.6 port 8080
      #- dfw.output.rule.3=deny on eth0 to 0.0.0.0/0
    networks:
      - firewall-macvlan

networks:
  firewall-bridge:
    driver: bridge
  firewall-macvlan:
    driver: macvlan
    driver_opts:
      parent: enp89s0
    ipam:
      config:
        - subnet: 192.168.110.0/24
          ip_range: 192.168.110.0/24
          gateway: 192.168.110.1
